title: Daniel Oto-Peralías
description: Associate Professor in Economics, Univ. Pablo de Olavide (Seville)
logo: /logo.jpg_1690923411.jpg
show_downloads: false
google_analytics: UA-56229081-1
theme: jekyll-theme-minimal
