title: Daniel Oto-Peralías
logo: /logo.jpg_1690923411.jpg
description: Associate Professor in Economics, Univ. Pablo de Olavide (Seville)
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
